spring:
  application:
    name: configServer
  profiles:
    active: dev,mysql
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jjh000gx/algorithm
          timeout: 20
          skipSslValidation: true
          search-paths: /springcloud/configfile
