server:
  port: 8091
spring:
  application:
    name: configServer
  profiles:
    #active: dev,mysql
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jjh000gx/algorithm
          #file://${user.home}/config-repo 本地文件路径配置
          timeout: 20
          skipSslValidation: true
          search-paths: '/springcloud/configfile'
